services:
  - type: web
    name: excaliber-api
    runtime: node
    buildCommand: npm install && npm run build --workspace=server
    startCommand: npm run start --workspace=server
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PEXELS_API_KEY
        sync: false
      - key: CLIENT_URL
        sync: false
